# Generated by Django 6.1 on 2026-09-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='invite_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
